### ISSUE TITLE
why don't close respQueue after the Session closed?

### ISSUE THREAD

**Issue by cyheng** [DarthPestilane/easytcp#34]
i found  the respQueue  chan  was created in session struct
```
type session struct {
	id          interface{}   // session's ID.
	conn        net.Conn      // tcp connection
	closed      chan struct{} // to close()
	closeOnce   sync.Once     // ensure one session only close once
	respQueue   chan Context  // response queue channel, pushed in Send() and popped in writeOutbound()
	packer      Packer        // to pack and unpack message
	codec       Codec         // encode/decode message data
	ctxPool     sync.Pool     // router context pool
	asyncRouter bool          // calls router HandlerFunc in a goroutine if false
}
```

but it doesn't close  when calling  the  session close function 
```
// Close closes the session, but doesn't close the connection.
// The connection will be closed in the server once the session's closed.
func (s *session) Close() {
	s.closeOnce.Do(func() { close(s.closed) })
}
```

Could you tell me your design about it, many thanks.

**Comment by DarthPestilane** [comment]
Leave `respQueue` channel open is because:

```go
// Send pushes response message entry to respQueue.
// Returns false if session is closed or ctx is done.
func (s *session) Send(ctx Context) (ok bool) {
	select {
	case <-ctx.Done():
		return false
	case <-s.closed:
		return false
	case s.respQueue <- ctx:
		return true
	}
}
```

In `Send` method, it will try to push ctx to `respQueue` channel, it can cause a panic if the channel is closed.

And it's ok to keep a channel open.

**Comment by cyheng** [comment]
thanks for your reply. And i have found the relative topic on [stackoverflow](https://stackoverflow.com/questions/8593645/is-it-ok-to-leave-a-channel-open).
I'm consider it might lead to the memory leak.

**Comment by DarthPestilane** [comment]
I don't think there will be memory leak, have tested already.
All goroutines will exit once the session's closed or the server's stopped.
