### ISSUE TITLE
Help with install

### ISSUE THREAD

**Issue by AshKetchumPL** [DarthPestilane/easytcp#44]
i got an error running my main.go
after i run the command nothing changed

error:

main.go:6:5: no required module provides package github.com/DarthPestilane/easytcp/message; to add it:
        go get github.com/DarthPestilane/easytcp/message

**Comment by DarthPestilane** [comment]
Try not import "github.com/DarthPestilane/easytcp/message", the README is outdated.

**Comment by DarthPestilane** [comment]
the README is updated
