### ISSUE TITLE
Q: sesdion context usage guide or example

### ISSUE THREAD

**Issue by tkang007** [DarthPestilane/easytcp#47]
Dear contributors,
Could you help me how to use session context or any other way  to reference its starting initial  request or response mesage until the end of coversation ?
Exsmple code will be big help to me and others.
Appreviate!!!

**Comment by DarthPestilane** [comment]
Maybe you can checkout code in examples here: https://github.com/DarthPestilane/easytcp/tree/master/internal/examples/tcp

**Comment by tkang007** [comment]
Great!  I found an example at, https://github.com/DarthPestilane/easytcp/tree/master/internal/examples/tcp/broadcast.

If we have a session level storage just like message and router, it might be more convenient for the usage scenario, referencing start/first message on the following message/conversation.

How about changing Unpack's io.EOF case logging level from ERROR to INFO or DEBUG for client closing case ?

Thanks!

**Comment by DarthPestilane** [comment]
@tkang007  can you show some code about the using case of session level storage?
